/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.rameon.sing.opensl;

public class SingModule {
  public static void start_base_process() {
    SingModuleJNI.start_base_process();
  }

  public static void stop_base_process() {
    SingModuleJNI.stop_base_process();
  }

  public static void start_inst_process() {
    SingModuleJNI.start_inst_process();
  }

  public static void stop_inst_process() {
    SingModuleJNI.stop_inst_process();
  }

}
