/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.rameon.sing.opensl;

public class SingModuleJNI {

  static {
    try {
        java.lang.System.loadLibrary("Sing");
    } catch (UnsatisfiedLinkError e) {
        java.lang.System.err.println("native code library failed to load.\n" + e);
        java.lang.System.exit(1);
    }
  }

  public final static native void start_base_process();
  public final static native void stop_base_process();
  public final static native void start_inst_process();
  public final static native void stop_inst_process();
}
